### PR TITLE
Add recipe maintainers

### PR DESCRIPTION
**Pull request by koverholt**
@martindurant and @mrocklin, can you confirm your addition as maintainers to this recipe?

### CODE REVIEW

**Comment by martindurant** [comment]
confirm

**Comment by koverholt** [comment]
Adding @mrocklin as a maintainer per https://github.com/conda-forge/staged-recipes/issues/139#issuecomment-220803503.

**Comment by mrocklin** [comment]
Gah!  Tricked by my own words!

**Comment by koverholt** [comment]
Yes, loophole found. :)

Just trying to increase the bus factor on this recipe.

**Pull request merged**
